import {stagingBP} from './stagingBP'
const staging = new stagingBP()

describe ('Create and apply an adjustment', () => {
    test('', async() =>{
        await staging.navigate()
        await staging.click(staging.userName)
        await staging.setInput(staging.userName, "scandata@goftx.com")
        await staging.click(staging.password)
        await staging.setInput(staging.password, "FasTrax0!")
        await staging.click(staging.signIn)
        await staging.click(staging.hamMenu)
        await staging.click(staging.posMenu)
        await staging.click(staging.invMenu)
        await staging.click(staging.adjustmentMenu)
        await staging.click(staging.addNew)
        await staging.click(staging.memo)
        await staging.setInput(staging.memo, "This is a memo")
        await staging.click(staging.locationDrop)
        await staging.click(staging.locationSelect)
        await staging.click(staging.adjustmentReason)
        await staging.setInput(staging.adjustmentReason, "This is a reason")
        await staging.click(staging.searchProduct1)
        await staging.setInput(staging.searchProduct1, "123123\n")
        await staging.driver.sleep(3000)
        await staging.click(staging.add)
        await staging.click(staging.applyAdjustment)
    })
})